### ISSUE TITLE
Help me understand Scenarios without Givens

### ISSUE THREAD

**Issue by eternalmatt** [denford/TuteCumber#1]
Hi @denford wonderful tutorial!
This isn't really an "issue" but I was wondering if you could help me understand the two scenarios in stage 3 without "Given" lines

https://github.com/denford/TuteCumber/blob/Stage3/features/multiple_operations.feature#L34-L44

Is it
1. they work without any given step execution
or
2. they work against ALL Given steps (resulting in N tests for N Given steps)

Thanks.  If this can be explained clearly, we could do a whole github-style pull request thing and update the repo with more tutorialness.

**Comment by denford** [comment]
Hi @eternalmatt - thanks very much.

The intention of the given clause is that it represents a "pre-condition", that basically puts the system into a known _current state_. My intention in leaving out the Given clause is that I'm saying "this should happen regardless of what the _current state_ is". Now that you've brought it up I need to see if this is really a valid way to model this, or if there should always be a Given clause.

To answer your specific question, it just works without any given step execution, so option 1. Under the hood the way it works is that each of the Given/When/Then clauses basically translate into single step that executes. E.g. when you have a simple single scenario like:

```
  Scenario: Multiple Addition and subtraction result negative
    Given the calculator is cleared
    When I subtract 65 from 34
    And then add 45
    And then subtract 87
    Then the result should be -73
```

And you run the test, you get:

``` bash
1 scenario (1 passed)
5 steps (5 passed)
```

5 Steps: that is, 1 x `Given` + 3 x `When` (2 of which are `And`) + 1 x `Then` = 5 steps total. Taking out that Given and running again just leaves 4 steps.

So from the point of view of executing the actual tests, it just executes one less step when there is no Given clause, and all that means is one less Step Definition, and just happily goes on executing the other step definitions and checking the result at the end.

As I said above, I'll look more into whether leaving out a Given clause is a valid way.

Incidentally, you could somewhat demonstrate this if you made the following changes. In calc.coffee:

``` CoffeeScript
class Calc
  _currentSum: 0
```

Becomes:

``` CoffeeScript
class Calc
  _currentSum: 42
```

So we initialise the calculator's current sum to some non-zero value, then instead of the scenario above, we change it to not have the given clause:

```
  Scenario: Multiple Addition and subtraction result negative
    When I subtract 65 from 34
    And then add 45
    And then subtract 87
    Then the result should be -73
```

Then re-run the tests we get:

``` bash
1 scenario (1 failed)
4 steps (1 failed, 3 passed)
```

That is, it fails because that scenario needed that pre-condition of clearing the calculator to be there, but if we run the scenarios that you initially asked about we get them passing still, even though they don't have the given clause, because they are trying to describe a scenario that works regardless of the current state:

```
  Scenario: Clear resets result to zero
    When the calculator is cleared
    Then the result should be 0

  Scenario: Clear resets result to zero after complex operations
    When I add 5 and 6
    And then add 65
    And then subtract 4055
    And then add 3404
    And the calculator is cleared
    Then the result should be 0
```

``` bash
2 scenarios (2 passed)
8 steps (8 passed)
```

Does that help clarify? I'm happy to add some more to the tutorial, and I'll look into Given-free scenarios!

**Comment by eternalmatt** [comment]
Thanks @denford , that does help clarify and I really appreciate you taking the time to give such a great response.

Side note, I think I also missed the fact that you were able to reuse the previous "Given the calculator is cleared" step as a When step. So having understood that, it makes a lot more sense how these scenarios are perfectly valid.

**Comment by denford** [comment]
Yep great - happy to help and think through it. For the sake of "process" I'll close out this "issue", feel free to reach out again etc.
